export const DEPRECATED_PREFIX = "tns-core-modules";
export const NEW_MODULE_PATH = "@nativescript/core";
export const RE_EXPORTED = Symbol("re-exported");
export const NESTED_MODULE_EXPORT = Symbol("deep-export");

export const DEPRECATED_PATH_MAP = {
    "tns-core-modules/application": "Application",
    "tns-core-modules/application-settings": "ApplicationSettings",
    "tns-core-modules/trace": "Trace",
    "tns-core-modules/http": "Http",
    "tns-core-modules/https": "Http",
    "tns-core-modules/connectivity": "Connectivity",
    "tns-core-modules/color": RE_EXPORTED,
    "tns-core-modules/color/known-colors": NESTED_MODULE_EXPORT,
    "tns-core-modules/data/observable-array": RE_EXPORTED,
    "tns-core-modules/data/observable": RE_EXPORTED,
    "tns-core-modules/data/virtual-array": RE_EXPORTED,
    "tns-core-modules/file-system": RE_EXPORTED,
    "tns-core-modules/image-asset": RE_EXPORTED,
    "tns-core-modules/image-source": RE_EXPORTED,
    "tns-core-modules/module-name-resolver": RE_EXPORTED,
    "tns-core-modules/platform": RE_EXPORTED,
    "tns-core-modules/profiling": RE_EXPORTED,
    "tns-core-modules/text": RE_EXPORTED,
    "tns-core-modules/timer": "Utils",
    "tns-core-modules/utils": "Utils",
    "tns-core-modules/utils/types": "Utils",
    "tns-core-modules/xml": RE_EXPORTED,

    "tns-core-modules/ui/dialogs": "Dialogs",
    "tns-core-modules/ui/enums": "Enums",

    "tns-core-modules/ui/action-bar": RE_EXPORTED,
    "tns-core-modules/ui/activity-indicator": RE_EXPORTED,
    "tns-core-modules/ui/animation": RE_EXPORTED,
    "tns-core-modules/ui/bottom-navigation": RE_EXPORTED,
    "tns-core-modules/ui/builder": RE_EXPORTED,
    "tns-core-modules/ui/button": RE_EXPORTED,
    "tns-core-modules/ui/content-view": RE_EXPORTED,
    "tns-core-modules/ui/core": RE_EXPORTED,
    "tns-core-modules/ui/core/bindable": RE_EXPORTED,
    "tns-core-modules/ui/core/control-state-change": RE_EXPORTED,
    "tns-core-modules/ui/core/properties": RE_EXPORTED,
    "tns-core-modules/ui/core/view-base": RE_EXPORTED,
    "tns-core-modules/ui/core/view": RE_EXPORTED,
    "tns-core-modules/ui/core/weak-event-listener": RE_EXPORTED,
    "tns-core-modules/ui/date-picker": RE_EXPORTED,
    "tns-core-modules/ui/editable-text-base": RE_EXPORTED,
    "tns-core-modules/ui/frame": RE_EXPORTED,
    "tns-core-modules/ui/gestures": RE_EXPORTED,
    "tns-core-modules/ui/html-view": RE_EXPORTED,
    "tns-core-modules/ui/image-cache": RE_EXPORTED,
    "tns-core-modules/ui/image": RE_EXPORTED,
    "tns-core-modules/ui/label": RE_EXPORTED,
    "tns-core-modules/ui/list-picker": RE_EXPORTED,
    "tns-core-modules/ui/list-view": RE_EXPORTED,
    "tns-core-modules/ui/page": RE_EXPORTED,
    "tns-core-modules/ui/placeholder": RE_EXPORTED,
    "tns-core-modules/ui/progress": RE_EXPORTED,
    "tns-core-modules/ui/proxy-view-container": RE_EXPORTED,
    "tns-core-modules/ui/repeater": RE_EXPORTED,
    "tns-core-modules/ui/scroll-view": RE_EXPORTED,
    "tns-core-modules/ui/search-bar": RE_EXPORTED,
    "tns-core-modules/ui/segmented-bar": RE_EXPORTED,
    "tns-core-modules/ui/slider": RE_EXPORTED,
    "tns-core-modules/ui/styling": RE_EXPORTED,
    "tns-core-modules/ui/switch": RE_EXPORTED,
    "tns-core-modules/ui/tab-navigation-base": RE_EXPORTED,
    "tns-core-modules/ui/tab-view": RE_EXPORTED,
    "tns-core-modules/ui/tabs": RE_EXPORTED,
    "tns-core-modules/ui/text-base": RE_EXPORTED,
    "tns-core-modules/ui/text-field": RE_EXPORTED,
    "tns-core-modules/ui/text-view": RE_EXPORTED,
    "tns-core-modules/ui/time-picker": RE_EXPORTED,
    "tns-core-modules/ui/transition": RE_EXPORTED,
    "tns-core-modules/ui/web-view": RE_EXPORTED,

    "tns-core-modules/ui/layouts": RE_EXPORTED,
    "tns-core-modules/ui/layouts/absolute-layout": RE_EXPORTED,
    "tns-core-modules/ui/layouts/dock-layout": RE_EXPORTED,
    "tns-core-modules/ui/layouts/flexbox-layout": RE_EXPORTED,
    "tns-core-modules/ui/layouts/grid-layout": RE_EXPORTED,
    "tns-core-modules/ui/layouts/stack-layout": RE_EXPORTED,
    "tns-core-modules/ui/layouts/wrap-layout": RE_EXPORTED,
};

export const DEPRECATED_PATHS = Object.keys(DEPRECATED_PATH_MAP);

export const RE_EXPORTED_SPECIFIERS = [
    "AndroidApplication",
    "iOSApplication",

    "LaunchEventData",
    "ApplicationEventData",
    "OrientationChangedEventData",
    "UnhandledErrorEventData",

    "TraceWriter",
    "TraceEventListener",
    "TraceErrorHandler",

    "HttpRequestOptions",
    "HttpResponse",
    "Headers",
    "HttpResponseEncoding",
    "HttpContent",

    "ImageAssetOptions",

    "inputType",
    "capitalizationType",
    "CancelableOptions",
    "ActionOptions",
    "DialogOptions",
    "AlertOptions",
    "ConfirmOptions",
    "PromptOptions",
    "LoginOptions",
    "PromptResult",
    "LoginResult",
];

export const UPDATED_SPECIFIERS = {
    device: "Device",
    screen: "Screen",
    Device: "IDevice",
};
